### ISSUE TITLE
It looks like the readiness endpoint now requires a parameter

### ISSUE THREAD

**Issue by DerekK19** [KevinKrumbiegel/check_gitlab#1]
I ran the python module as is and got  the output:
Cache check: Status=unknown, Message=
Database check: Status=unknown, Message=
Gitaly check: Status=unknown, Message=
Queues check: Status=unknown, Message=
Redis check: Status=unknown, Message=
Shared state check: Status=unknown, Message=
6 checks done.

I then altered the check_gitlab file to append a ?all=1 argument to the readiness request so that it reads:

request = urllib.request.urlopen(server + "-/readiness?all=1")

Now when I run the module I get:
./check_gitlab -s http://127.0.0.1:8080/ --check-all
OK - All checks ok
6 checks done.

It looks like Gitlab now requires a ?all=1 query parameter or only the master_check status will be returned. Maybe the settings are different for checking the status of gitlab.com

I have the latest Gitlab EE install (13.4.4-ee.0)

**Comment by KevinKrumbiegel** [comment]
Thank you very much for that hint!
I just adapted the request as proposed by you.
